#!/usr/bin/env python3
"""Generate a Rust model manifest from TypeScript response/type declarations."""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
RESPONSES_DIR = REPO_ROOT / "src" / "responses"
TYPES_DIR = REPO_ROOT / "src" / "types"
OUTPUT_FILE = REPO_ROOT / "rust" / "src" / "models" / "generated" / "mod.rs"


def module_name(path: Path) -> str:
    return path.name.replace(".ts", "").replace(".", "_").replace("-", "_")


def build_manifest() -> tuple[list[str], list[str]]:
    response_modules = sorted(module_name(path) for path in RESPONSES_DIR.glob("*.ts"))
    type_modules = sorted(module_name(path) for path in TYPES_DIR.glob("*.ts"))
    return response_modules, type_modules


def render(response_modules: list[str], type_modules: list[str]) -> str:
    lines: list[str] = []
    lines.append("/// Auto-generated by `rust/scripts/generate_models.py`. Do not edit manually.")
    lines.append("pub const RESPONSE_MODULES: &[&str] = &[")
    for name in response_modules:
        lines.append(f'    "{name}",')
    lines.append("];\n")

    lines.append("pub const TYPE_MODULES: &[&str] = &[")
    for name in type_modules:
        lines.append(f'    "{name}",')
    lines.append("];\n")

    lines.append("pub fn manifest_counts() -> (usize, usize) {")
    lines.append("    (RESPONSE_MODULES.len(), TYPE_MODULES.len())")
    lines.append("}")

    return "\n".join(lines) + "\n"


def main() -> None:
    response_modules, type_modules = build_manifest()
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(render(response_modules, type_modules), encoding="utf-8")
    print(
        f"generated {OUTPUT_FILE.relative_to(REPO_ROOT)} "
        f"(responses={len(response_modules)}, types={len(type_modules)})"
    )


if __name__ == "__main__":
    main()
